Repository Ormi5-StrikeOut/Play-Baseball, pull requests merged in 2024-09, with the labels that each got.

#66 Chore: Spring CI.yml 에 JWT 관련 환경변수 추가
  .github/workflows/Spring CI.yml
Labels: 🔧 Chore

#68 Feat: JWT 기반 인증 시스템을 구현
  build.gradle
  src/main/java/org/example/spring/controller/AuthController.java
  src/main/java/org/example/spring/controller/MemberController.java
  src/main/java/org/example/spring/domain/member/dto/LoginRequestDto.java
  src/main/java/org/example/spring/security/CustomAccessDeniedHandler.java
  src/main/java/org/example/spring/security/CustomAuthenticationEntryPoint.java
  src/main/java/org/example/spring/security/SecurityConfig.java
  src/main/java/org/example/spring/security/jwt/CookieService.java
  src/main/java/org/example/spring/security/jwt/JwtAuthenticationService.java
  src/main/java/org/example/spring/security/jwt/JwtTokenProvider.java
  src/main/java/org/example/spring/security/jwt/JwtTokenValidator.java
  src/main/java/org/example/spring/security/jwt/JwtUtils.java
  src/main/java/org/example/spring/security/jwt/JwtValidatorFilter.java
  src/main/java/org/example/spring/service/AuthService.java
  src/main/resources/application.yml
Labels: ✨ Feature

#71 Docs: Security JWT 관련 자바독 추가
  src/main/java/org/example/spring/controller/AuthController.java
  src/main/java/org/example/spring/security/config/SecurityConfig.java
  src/main/java/org/example/spring/security/handler/CustomAccessDeniedHandler.java
  src/main/java/org/example/spring/security/handler/CustomAuthenticationEntryPoint.java
  src/main/java/org/example/spring/security/jwt/CookieService.java
  src/main/java/org/example/spring/security/jwt/JwtAuthenticationService.java
  src/main/java/org/example/spring/security/jwt/JwtTokenProvider.java
  src/main/java/org/example/spring/security/jwt/JwtTokenValidator.java
  src/main/java/org/example/spring/security/jwt/JwtUtils.java
  src/main/java/org/example/spring/security/jwt/JwtValidatorFilter.java
  src/main/java/org/example/spring/security/service/CustomUserDetailsService.java
  src/main/java/org/example/spring/security/service/CustomUsernamePasswordAuthenticationProvider.java
  src/main/java/org/example/spring/service/AuthService.java
  src/test/java/org/example/spring/security/CustomUserDetailsServiceTest.java
  src/test/java/org/example/spring/security/CustomUsernamePasswordAuthenticationProviderTest.java
Labels: 📝 Documentation

#73 Refactor: CORS 설정 securityFilterChain 에 통합
  src/main/java/org/example/spring/global/WebConfig.java
  src/main/java/org/example/spring/security/config/SecurityConfig.java
Labels: 🔨 Refactor

#75 Feat: SecurityConfig CORS 설정 강화
  src/main/java/org/example/spring/security/config/SecurityConfig.java
Labels: ✨ Feature

#76 Chore: dev 환경에서 CD 작동하도록 수정
  .github/workflows/FE CD.yml
  .github/workflows/Spring CD.yml
  .github/workflows/Spring CI.yml
Labels: 🔧 Chore

#79 Refactor: SecurityConfig Cors 오리진 변경
  src/main/java/org/example/spring/security/config/SecurityConfig.java
Labels: 🔨 Refactor

#84 Feat: CookieService refreshToken 생성시 sameSite 속성 설정
  src/main/java/org/example/spring/security/jwt/CookieService.java
Labels: ✨ Feature

#86 Feat: SecurityConfig headers 옵션 추가
  src/main/java/org/example/spring/security/config/SecurityConfig.java
Labels: ✨ Feature

#92 Fix: AuthController APi 앤드포인트 수정
  src/main/java/org/example/spring/controller/AuthController.java
Labels: 🐛 Bug Fix

#93 Feat: 게시글 작성 페이지 레이아웃
  fe/play-baseball-fe/pages/exchange/write/index.tsx
Labels: ✨ Feature, 💄 UI Design

#95 Refactor: AuthController APi 앤드포인트 수정
  src/main/java/org/example/spring/controller/AuthController.java
Labels: 🔨 Refactor

#105 Feat: 채팅방 페이지 레이아웃 작성
  fe/play-baseball-fe/pages/chat/[id].js
  fe/play-baseball-fe/pages/chat/index.tsx
Labels: ✨ Feature, 💄 UI Design

#103 Refactor: 로그인, 로그아웃 엔드포인트 상수값 변경
  fe/play-baseball-fe/constants/endpoints.tsx
Labels: 🔨 Refactor

#99 Refactor: SecurityConfig API 엔드포인트에 대한 보안 설정 개선 및 재구성
  src/main/java/org/example/spring/security/config/SecurityConfig.java
  src/main/java/org/example/spring/security/config/SecurityDevConfig.java
  src/test/java/org/example/spring/controller/ReviewControllerTest.java
Labels: 🔨 Refactor

#108 Refactor: Security Access Token set 로직 추가 및 디렉토리 구조변경
  src/main/java/org/example/spring/controller/AuthController.java
  src/main/java/org/example/spring/domain/member/dto/LoginResponseDto.java
  src/main/java/org/example/spring/security/config/SecurityConfig.java
  src/main/java/org/example/spring/security/config/SecurityDevConfig.java
  src/main/java/org/example/spring/security/filter/JwtValidatorFilter.java
  src/main/java/org/example/spring/security/service/JwtAuthenticationService.java
  src/main/java/org/example/spring/service/AuthService.java
Labels: 🔨 Refactor

#102 Feat: 헤더 레이아웃 제작
  fe/play-baseball-fe/components/header.tsx
  fe/play-baseball-fe/constants/endpoints.tsx
  fe/play-baseball-fe/package-lock.json
  fe/play-baseball-fe/package.json
  fe/play-baseball-fe/pages/_app.tsx
  fe/play-baseball-fe/pages/login/index.tsx
Labels: ✨ Feature, 💄 UI Design

#111 #110 Refactor: FE docker image 실행 시 포트번호 80 -> 8080으로 변경
  .github/workflows/FE CD.yml
Labels: 🔨 Refactor

#113 #112 Refactor: 회원가입 페이지 fetch -> axios 변경
  fe/play-baseball-fe/pages/signup/index.tsx
Labels: 🔨 Refactor

#114 Feat: Rate Limiting 구현 및 SecurityFilterChain에 통합
  build.gradle
  src/main/java/org/example/spring/constants/RateLimitBucketConstants.java
  src/main/java/org/example/spring/controller/AuthController.java
  src/main/java/org/example/spring/security/config/SecurityConfig.java
  src/main/java/org/example/spring/security/config/SecurityDevConfig.java
  src/main/java/org/example/spring/security/filter/JwtValidatorFilter.java
  src/main/java/org/example/spring/security/filter/RateLimitFilter.java
  src/main/java/org/example/spring/security/jwt/CookieService.java
  src/main/java/org/example/spring/security/jwt/JwtTokenValidator.java
  src/main/java/org/example/spring/security/jwt/JwtUtils.java
  src/main/java/org/example/spring/security/service/AuthService.java
  src/main/java/org/example/spring/security/service/JwtAuthenticationService.java
  src/main/java/org/example/spring/security/service/RateLimiterService.java
Labels: ✨ Feature

#117 Fix: Spring 서버 http -> https 무한 리디렉션 문제 해결
  src/main/java/org/example/spring/security/config/SecurityConfig.java
  src/main/java/org/example/spring/security/config/SecurityDevConfig.java
  src/main/resources/application.yml
Labels: 🐛 Bug Fix

#120 Refactor: Rate Limit 성능 최적화 및 캐싱 도입
  build.gradle
  src/main/java/org/example/spring/security/filter/RateLimitFilter.java
  src/main/java/org/example/spring/security/service/RateLimiterService.java
Labels: 🔨 Refactor

#122 Refactor: FE에 정의된 서버 URL과 요청할 api url 값 변경
  fe/play-baseball-fe/constants/endpoints.tsx
Labels: 🔨 Refactor

#124 Fix: Cors Origin url 추가
  src/main/java/org/example/spring/security/config/SecurityConfig.java
Labels: 🐛 Bug Fix

#125 Fix: SecurityConfig failureUrl 삭제
  src/main/java/org/example/spring/security/config/SecurityConfig.java
Labels: 🐛 Bug Fix

#126 Fix: SecurityConfig 임시 홈 경로 모두 공해
  src/main/java/org/example/spring/security/config/SecurityConfig.java
Labels: 🐛 Bug Fix

#127 Refactor: RateLimit 관련 코드 리펙터링
  src/main/java/org/example/spring/security/service/RateLimiterService.java
Labels: 🔨 Refactor

#130 Fix: SecurityConfig "/" 경로 모두 허용
  src/main/java/org/example/spring/security/config/SecurityConfig.java
Labels: 🐛 Bug Fix

#132 #131 Fix: 무한 리디렉션 관련 해결을 위한 yml 헤더 검사내용 추가
  src/main/resources/application.yml
Labels: 🐛 Bug Fix

#134 Fix: SecurityConfig Caddy 사용으로 requiresChannel 제거
  src/main/java/org/example/spring/security/config/SecurityConfig.java
Labels: 🐛 Bug Fix

#135 Fix: endpoints url 누락 부분 수정
  fe/play-baseball-fe/constants/endpoints.tsx
Labels: 🐛 Bug Fix

#138 Fix: 공개 api jwt 검증 예외 설정 및 Cors 허용 헤더 추가
  src/main/java/org/example/spring/security/config/SecurityConfig.java
  src/main/java/org/example/spring/security/filter/JwtValidatorFilter.java
Labels: 🐛 Bug Fix

#140 #131 Fix: AllowedOrigins 내용에 http 추가
  src/main/java/org/example/spring/security/config/SecurityConfig.java
Labels: 🐛 Bug Fix

#141 #131 Fix: springconfig http.headers 내용 변경
  src/main/java/org/example/spring/security/config/SecurityConfig.java
Labels: 🐛 Bug Fix

#142 #131 Fix: headers compile error
  src/main/java/org/example/spring/security/config/SecurityConfig.java
Labels: 🐛 Bug Fix

#143 Fix: setAllowedMethods 내용에 OPTIONS 추가
  src/main/java/org/example/spring/security/config/SecurityConfig.java
Labels: 🐛 Bug Fix

#144 #131 Fix: application.yml debug 내용 추가
  src/main/resources/application.yml
Labels: 🐛 Bug Fix

#145 Fix: https 통신 정상화
  fe/play-baseball-fe/pages/login/index.tsx
  fe/play-baseball-fe/pages/signup/index.tsx
  src/main/java/org/example/spring/security/config/SecurityConfig.java
Labels: 🐛 Bug Fix

#146 Feat: Logout 기능 구현
  src/main/java/org/example/spring/controller/AuthController.java
  src/main/java/org/example/spring/exception/InvalidTokenException.java
  src/main/java/org/example/spring/security/config/SecurityConfig.java
  src/main/java/org/example/spring/security/config/SecurityDevConfig.java
  src/main/java/org/example/spring/security/filter/JwtValidatorFilter.java
  src/main/java/org/example/spring/security/handler/CustomAuthenticationEntryPoint.java
  src/main/java/org/example/spring/security/jwt/CookieService.java
  src/main/java/org/example/spring/security/jwt/JwtTokenValidator.java
  src/main/java/org/example/spring/security/jwt/JwtUtils.java
  src/main/java/org/example/spring/security/service/AuthService.java
  src/main/resources/application.yml
Labels: ✨ Feature

#148 Test: 로그인 로그아웃 테스트 작성
  src/test/java/org/example/spring/controller/AuthControllerTest.java
  src/test/java/org/example/spring/repository/MemberRepositoryTest.java
  src/test/java/org/example/spring/security/service/AuthServiceTest.java
Labels: ✅ Test

#149 Chore: Update Spring CD.yml
  .github/workflows/Spring CD.yml
Labels: 🔧 Chore

#151 Chore: Update Spring CI.yml
  .github/workflows/Spring CI.yml
Labels: 🔧 Chore

#152 Fix: 로그아웃 API 정상화, 로그인 후 페이지 이동 시 header 부분에 반영이 되어있지 않던 점 수정
  fe/play-baseball-fe/components/header.tsx
  fe/play-baseball-fe/pages/login/index.tsx
Labels: 🐛 Bug Fix

#156 Refactor: UsenamePasswordAuthenticationToken 관련 전반적인 코드 리펙터링
  src/main/java/org/example/spring/domain/member/dto/LoginResponseDto.java
  src/main/java/org/example/spring/security/filter/JwtValidatorFilter.java
  src/main/java/org/example/spring/security/filter/RateLimitFilter.java
  src/main/java/org/example/spring/security/jwt/JwtTokenValidator.java
  src/main/java/org/example/spring/security/jwt/JwtUtils.java
  src/main/java/org/example/spring/security/service/AuthService.java
  src/main/java/org/example/spring/security/service/JwtAuthenticationService.java
  src/main/java/org/example/spring/service/MessageService.java
  src/test/java/org/example/spring/security/service/AuthServiceTest.java
Labels: 🔨 Refactor

#158 Refactor: JWT 인증 및 인가 시스템 전반적 리팩토링
  .github/workflows/Spring CI.yml
  src/main/java/org/example/spring/domain/member/Member.java
  src/main/java/org/example/spring/domain/member/dto/LoginResponseDto.java
  src/main/java/org/example/spring/exception/AuthenticationFailedException.java
  src/main/java/org/example/spring/exception/InvalidCredentialsException.java
  src/main/java/org/example/spring/exception/ResourceNotFoundException.java
  src/main/java/org/example/spring/security/filter/JwtValidatorFilter.java
  src/main/java/org/example/spring/security/filter/RateLimitFilter.java
  src/main/java/org/example/spring/security/jwt/JwtTokenProvider.java
  src/main/java/org/example/spring/security/jwt/JwtTokenValidator.java
  src/main/java/org/example/spring/security/service/AuthService.java
  src/main/java/org/example/spring/security/service/JwtAuthenticationService.java
  src/main/java/org/example/spring/security/service/RateLimiterService.java
  src/test/java/org/example/spring/controller/AuthControllerTest.java
  src/test/java/org/example/spring/security/service/AuthServiceTest.java
Labels: 🔨 Refactor

#163 Feat: 메인 페이지 레이아웃 추가, Global CSS 내용 추가
  fe/play-baseball-fe/components/header.tsx
  fe/play-baseball-fe/pages/_app.tsx
  fe/play-baseball-fe/pages/index.tsx
  fe/play-baseball-fe/pages/login/index.tsx
Labels: 💄 UI Design

#162 Update Spring CD.yml
  .github/workflows/Spring CD.yml
Labels: 🐛 Bug Fix

#164 Fix: 스웨거 contentSecurityPolicy 관련 오류 수정 및 review, exchanges 401 에러 수정
  src/main/java/org/example/spring/security/config/SecurityConfig.java
  src/main/java/org/example/spring/security/config/SecurityDevConfig.java
  src/main/java/org/example/spring/security/filter/JwtValidatorFilter.java
Labels: 🐛 Bug Fix

#167 Feat: 회원 탈퇴 기능 구현
  src/main/java/org/example/spring/common/GlobalExceptionHandler.java
  src/main/java/org/example/spring/constants/RateLimitBucketConstants.java
  src/main/java/org/example/spring/controller/AuthController.java
  src/main/java/org/example/spring/controller/MemberController.java
  src/main/java/org/example/spring/domain/member/Member.java
  src/main/java/org/example/spring/exception/AccountBannedException.java
  src/main/java/org/example/spring/exception/AccountDeletedException.java
  src/main/java/org/example/spring/security/config/SecurityConfig.java
  src/main/java/org/example/spring/security/config/SecurityDevConfig.java
  src/main/java/org/example/spring/security/filter/JwtValidatorFilter.java
  src/main/java/org/example/spring/security/filter/MemberStatusCheckFilter.java
  src/main/java/org/example/spring/security/filter/RateLimitFilter.java
  src/main/java/org/example/spring/security/jwt/CookieService.java
  src/main/java/org/example/spring/security/jwt/JwtTokenValidator.java
  src/main/java/org/example/spring/security/service/IpChangeDetectionService.java
  src/main/java/org/example/spring/security/service/JwtAuthenticationService.java
  src/main/java/org/example/spring/security/utils/AuthUtils.java
  src/main/java/org/example/spring/service/AuthService.java
  src/main/java/org/example/spring/service/MemberService.java
Labels: ✨ Feature

#168 Refactor: 액세스 토큰 재발급 시 응답 메세지 개선
  src/main/java/org/example/spring/common/GlobalExceptionHandler.java
  src/main/java/org/example/spring/security/filter/JwtValidatorFilter.java
  src/main/java/org/example/spring/security/filter/MemberStatusCheckFilter.java
  src/main/java/org/example/spring/security/jwt/JwtTokenValidator.java
  src/main/java/org/example/spring/security/service/JwtAuthenticationService.java
Labels: ✨ Feature

#169 Feat: 회원 정보 수정 기능 구현
  src/main/java/org/example/spring/common/GlobalExceptionHandler.java
  src/main/java/org/example/spring/controller/MemberController.java
  src/main/java/org/example/spring/domain/member/Member.java
  src/main/java/org/example/spring/domain/member/dto/MemberModifyRequestDto.java
  src/main/java/org/example/spring/domain/member/dto/MemberResponseDto.java
  src/main/java/org/example/spring/security/filter/JwtValidatorFilter.java
  src/main/java/org/example/spring/security/service/JwtAuthenticationService.java
  src/main/java/org/example/spring/service/MemberService.java
Labels: ✨ Feature

#170 Refactor: Exchange 관련 기능 완성
  src/main/java/org/example/spring/controller/ExchangeController.java
  src/main/java/org/example/spring/domain/exchange/Exchange.java
  src/main/java/org/example/spring/domain/exchange/dto/ExchangeAddRequestDto.java
  src/main/java/org/example/spring/domain/exchange/dto/ExchangeModifyRequestDto.java
  src/main/java/org/example/spring/domain/exchange/dto/ExchangeRequestDto.java
  src/main/java/org/example/spring/domain/exchange/dto/ExchangeResponseDto.java
  src/main/java/org/example/spring/domain/exchangeImage/ExchangeImage.java
  src/main/java/org/example/spring/domain/exchangeImage/dto/ExchangeImageResponseDto.java
  src/main/java/org/example/spring/repository/ExchangeImageRepository.java
  src/main/java/org/example/spring/repository/ExchangeRepository.java
  src/main/java/org/example/spring/service/ExchangeImageService.java
  src/main/java/org/example/spring/service/ExchangeService.java
  src/test/java/org/example/spring/controller/ExchangeControllerTest.java
  src/test/java/org/example/spring/controller/ReviewControllerTest.java
  src/test/java/org/example/spring/repository/ExchangeRepositoryTest.java
  src/test/java/org/example/spring/repository/ReviewRepositoryTest.java
  src/test/java/org/example/spring/service/ExchangeServiceTest.java
  src/test/java/org/example/spring/service/ReviewServiceTest.java
Labels: ✨ Feature, 🔨 Refactor

#171 Feat: 회권 권한 수정 기능 구현
  src/main/java/org/example/spring/common/GlobalExceptionHandler.java
  src/main/java/org/example/spring/controller/MemberController.java
  src/main/java/org/example/spring/domain/member/Member.java
  src/main/java/org/example/spring/domain/member/dto/MemberRoleModifyRequestDto.java
  src/main/java/org/example/spring/service/MemberService.java
Labels: ✨ Feature

#176 Refactor: 리뷰 등록 및 수정 시 권한 확인
  src/main/java/org/example/spring/controller/ReviewController.java
  src/main/java/org/example/spring/domain/review/Review.java
  src/main/java/org/example/spring/domain/review/dto/CreateReviewRequest.java
  src/main/java/org/example/spring/service/ReviewService.java
Labels: 🔨 Refactor

#175 Feat: 이메일 인증 구현
  .github/workflows/Spring CD.yml
  .github/workflows/Spring CI.yml
  .gitignore
  build.gradle
  src/main/java/org/example/spring/common/GlobalExceptionHandler.java
  src/main/java/org/example/spring/controller/MemberController.java
  src/main/java/org/example/spring/domain/member/Member.java
  src/main/java/org/example/spring/domain/member/dto/MemberEmailVerifiedResponseDto.java
  src/main/java/org/example/spring/domain/member/dto/MemberResponseDto.java
  src/main/java/org/example/spring/exception/EmailAlreadyVerifiedException.java
  src/main/java/org/example/spring/exception/EmailVerificationTokenExpiredException.java
  src/main/java/org/example/spring/exception/MemberNotFoundException.java
  src/main/java/org/example/spring/security/config/MailConfig.java
  src/main/java/org/example/spring/security/config/MailDevConfig.java
  src/main/java/org/example/spring/security/config/SecurityConfig.java
  src/main/java/org/example/spring/security/config/SecurityDevConfig.java
  src/main/java/org/example/spring/security/filter/JwtValidatorFilter.java
  src/main/java/org/example/spring/security/filter/MemberStatusCheckFilter.java
  src/main/java/org/example/spring/security/jwt/JwtTokenValidator.java
  src/main/java/org/example/spring/security/service/CookieService.java
  src/main/java/org/example/spring/security/service/EmailService.java
  src/main/java/org/example/spring/security/utils/JwtUtils.java
  src/main/java/org/example/spring/service/AuthService.java
  src/main/java/org/example/spring/service/MemberService.java
  src/main/resources/application-prod.yml
  src/test/java/org/example/spring/ApplicationTests.java
  src/test/java/org/example/spring/controller/MemberControllerTest.java
  src/test/java/org/example/spring/service/MemberServiceTest.java
  src/test/resources/application.yml
Labels: ✨ Feature

#179 Refactor: JwtValidatorFilter 리펙터링
  src/main/java/org/example/spring/security/filter/JwtValidatorFilter.java
  src/main/java/org/example/spring/security/jwt/JwtTokenValidator.java
  src/main/java/org/example/spring/security/service/AccountManagementService.java
  src/main/java/org/example/spring/security/service/TokenBlacklistService.java
  src/main/java/org/example/spring/service/AuthService.java
  src/main/java/org/example/spring/service/MemberService.java
  src/test/java/org/example/spring/service/MemberServiceTest.java
Labels: 🔨 Refactor

#182 Feat: 회원정보 3일 후 폐기 기능 구현
  .github/workflows/Spring CD.yml
  src/main/java/org/example/spring/Application.java
  src/main/java/org/example/spring/repository/MemberRepository.java
  src/main/java/org/example/spring/security/service/EmailService.java
  src/main/java/org/example/spring/service/MemberService.java
  src/main/resources/application-prod.yml
Labels: ✨ Feature

#185 Chore: application-prod.yml 설정 추가
  src/main/resources/application-prod.yml
Labels: 🔧 Chore

#186 Chore: Spring CD.yml update
  .github/workflows/Spring CD.yml
Labels: 🔧 Chore

#187 Chore: application-prod.yml update
  src/main/resources/application-prod.yml
Labels: 🔧 Chore

#189 Fix: 인증 관련 오류 해결 및 비밀번호 재설정 기능 구현
  src/main/java/org/example/spring/common/GlobalExceptionHandler.java
  src/main/java/org/example/spring/controller/MemberController.java
  src/main/java/org/example/spring/domain/member/Member.java
  src/main/java/org/example/spring/domain/member/MemberRole.java
  src/main/java/org/example/spring/domain/member/dto/EmailRequestDto.java
  src/main/java/org/example/spring/domain/member/dto/MemberModifyRequestDto.java
  src/main/java/org/example/spring/domain/member/dto/PasswordResetRequestDto.java
  src/main/java/org/example/spring/security/config/SecurityConfig.java
  src/main/java/org/example/spring/security/config/SecurityDevConfig.java
  src/main/java/org/example/spring/security/filter/JwtValidatorFilter.java
  src/main/java/org/example/spring/security/filter/MemberStatusCheckFilter.java
  src/main/java/org/example/spring/security/handler/CustomAccessDeniedHandler.java
  src/main/java/org/example/spring/security/handler/CustomAuthenticationEntryPoint.java
  src/main/java/org/example/spring/security/service/CustomUserDetailsService.java
  src/main/java/org/example/spring/security/service/EmailService.java
  src/main/java/org/example/spring/service/AuthService.java
  src/main/java/org/example/spring/service/MemberService.java
  src/test/java/org/example/spring/controller/MemberControllerTest.java
  src/test/java/org/example/spring/service/MemberServiceTest.java
  src/test/resources/application.yml
Labels: 🐛 Bug Fix

#191 Update Spring CD.yml
  .github/workflows/Spring CD.yml
Labels: 🔧 Chore

#193 Refatctor: 메인 페이지 jwt 필터 제외 및 GlobalExceptionHandler 로깅 수정
  src/main/java/org/example/spring/common/GlobalExceptionHandler.java
  src/main/java/org/example/spring/security/filter/JwtValidatorFilter.java
Labels: ✨ Feature

#197 Fix: 게시물 조회 상세 페이지 충돌 수정
  fe/play-baseball-fe/pages/exchange/[id].tsx
Labels: 🐛 Bug Fix

#199 Fix: BE CD Deloy 명령어 수정 및 공개 엔드포인트 필터 스킵 처리
  .github/workflows/Spring CD.yml
  src/main/java/org/example/spring/security/filter/JwtValidatorFilter.java
  src/main/java/org/example/spring/security/filter/MemberStatusCheckFilter.java
Labels: 🐛 Bug Fix

#200 Fix: BE CD 명령어 수정
  .github/workflows/Spring CD.yml
Labels: 🐛 Bug Fix

#203 Fix: 게시물 상세조회 링크 www 제거, 링크 프로파일에 따라 작동하도록 yml 작성
  src/main/java/org/example/spring/domain/exchange/dto/ExchangeNavigationResponseDto.java
  src/main/java/org/example/spring/service/ExchangeService.java
  src/main/resources/application-prod.yml
Labels: 🐛 Bug Fix

#205 Feat: 의존성 추가 및 CD workflow 수정
  .github/workflows/Spring CD.yml
  build.gradle
Labels: 🐛 Bug Fix

#206 Feat: 게시물 상세 조회 실제 데이터 연동 작업
  fe/play-baseball-fe/pages/exchange/[id].tsx
  fe/play-baseball-fe/pages/exchange/write/[id].tsx
  fe/play-baseball-fe/pages/exchange/write/index.tsx
  src/main/java/org/example/spring/controller/ExchangeController.java
  src/main/java/org/example/spring/domain/exchange/dto/ExchangeDetailResponseDto.java
  src/main/java/org/example/spring/domain/exchange/dto/ExchangeNavigationResponseDto.java
  src/main/java/org/example/spring/repository/ExchangeRepository.java
  src/main/java/org/example/spring/service/ExchangeService.java
Labels: ✨ Feature

#208 Fix: FE 영역 빌드 에러 문제 수정
  fe/play-baseball-fe/components/UserProfile.tsx
  fe/play-baseball-fe/pages/_app.tsx
  fe/play-baseball-fe/pages/exchange/[id].tsx
Labels: 🐛 Bug Fix

#210 Refactor: Exchange 관련 BE 코드 모두 naver style 적용
  src/main/java/org/example/spring/constants/SalesStatus.java
  src/main/java/org/example/spring/controller/ExchangeController.java
  src/main/java/org/example/spring/domain/exchange/Exchange.java
  src/main/java/org/example/spring/domain/exchange/dto/ExchangeAddRequestDto.java
  src/main/java/org/example/spring/domain/exchange/dto/ExchangeDetailResponseDto.java
  src/main/java/org/example/spring/domain/exchange/dto/ExchangeModifyRequestDto.java
  src/main/java/org/example/spring/domain/exchange/dto/ExchangeNavigationResponseDto.java
  src/main/java/org/example/spring/domain/exchange/dto/ExchangeResponseDto.java
  src/main/java/org/example/spring/domain/exchangeImage/ExchangeImage.java
  src/main/java/org/example/spring/domain/exchangeImage/dto/ExchangeImageResponseDto.java
  src/main/java/org/example/spring/repository/ExchangeImageRepository.java
  src/main/java/org/example/spring/repository/ExchangeRepository.java
  src/main/java/org/example/spring/service/ExchangeImageService.java
  src/main/java/org/example/spring/service/ExchangeService.java
Labels: 🔨 Refactor

#212 Feat: AWS S3 스토리지를 이용한 이미지 관리 기능 제작
  .github/workflows/Spring CD.yml
  .github/workflows/Spring CI.yml
  build.gradle
  fe/play-baseball-fe/next.config.mjs
  src/main/java/org/example/spring/config/S3Config.java
  src/main/java/org/example/spring/service/ExchangeService.java
  src/main/java/org/example/spring/service/S3Service.java
  src/main/resources/application-prod.yml
Labels: ✨ Feature

#219 Refactor: 이미지 관련 Service 메서드 로직 통합
  src/main/java/org/example/spring/service/ExchangeService.java
  src/main/java/org/example/spring/service/ReviewService.java
  src/main/java/org/example/spring/service/S3Service.java
Labels: 🔨 Refactor

#224 Fix: JwtValidatorFilter shouldNotFilter 경로 추가
  src/main/java/org/example/spring/security/filter/JwtValidatorFilter.java
Labels: 🐛 Bug Fix

#225 Chore: build.gradle 잠재 충돌 위험 제거
  build.gradle
Labels: 🐛 Bug Fix

#232 Feat: SecurityConfig 경로 추가
  src/main/java/org/example/spring/security/config/SecurityConfig.java
  src/main/java/org/example/spring/security/config/SecurityDevConfig.java
  src/main/java/org/example/spring/security/service/IpChangeDetectionService.java
  src/main/java/org/example/spring/security/service/JwtAuthenticationService.java
Labels: ✨ Feature

#233 Feat: 이메일 인증 UI 구현
  .github/workflows/Spring CD.yml
  fe/play-baseball-fe/.env.prod
  fe/play-baseball-fe/components/axiosInstance.tsx
  fe/play-baseball-fe/constants/endpoints.tsx
  fe/play-baseball-fe/pages/login/index.tsx
  fe/play-baseball-fe/pages/resend-verify-email.tsx
  fe/play-baseball-fe/pages/result/result-page.tsx
  fe/play-baseball-fe/pages/verify-email.tsx
  src/main/java/org/example/spring/controller/MemberController.java
  src/main/java/org/example/spring/security/config/SecurityConfig.java
  src/main/java/org/example/spring/security/config/SecurityDevConfig.java
  src/main/java/org/example/spring/security/filter/JwtValidatorFilter.java
  src/main/java/org/example/spring/security/filter/MemberStatusCheckFilter.java
  src/main/java/org/example/spring/security/filter/RateLimitFilter.java
  src/main/java/org/example/spring/security/service/EmailService.java
  src/main/java/org/example/spring/service/MemberService.java
  src/test/java/org/example/spring/controller/MemberControllerTest.java
Labels: ✨ Feature

#234 Chore: BE FE CD workflow 수정
  .github/workflows/FE CD.yml
  .github/workflows/Spring CD.yml
Labels: 🔧 Chore

#236 Feat: 메인 페이지 디자인 전반, 글 삭제, 수정 버그 수정,
  fe/play-baseball-fe/package-lock.json
  fe/play-baseball-fe/package.json
  fe/play-baseball-fe/pages/exchange/[id].tsx
  fe/play-baseball-fe/pages/exchange/write/[id].tsx
  fe/play-baseball-fe/pages/exchange/write/index.tsx
  fe/play-baseball-fe/pages/index.tsx
  src/main/java/org/example/spring/constants/SalesStatus.java
  src/main/java/org/example/spring/controller/ExchangeController.java
  src/main/java/org/example/spring/domain/exchange/Exchange.java
  src/main/java/org/example/spring/domain/exchange/dto/ExchangeNavigationResponseDto.java
  src/main/java/org/example/spring/domain/exchange/dto/ExchangeResponseDto.java
  src/main/java/org/example/spring/repository/ExchangeRepository.java
  src/main/java/org/example/spring/service/ExchangeService.java
Labels: ✨ Feature, 🔨 Refactor, 💄 UI Design

#237 Fix: header.tsx 오류 수정
  fe/play-baseball-fe/components/header.tsx
  fe/play-baseball-fe/constants/endpoints.tsx
Labels: 🐛 Bug Fix

#241 Feat: FE 비밀번호 재설정 UI 구현
  fe/play-baseball-fe/components/PasswordResetForm.tsx
  fe/play-baseball-fe/components/RequestPasswordReset.tsx
  fe/play-baseball-fe/constants/endpoints.tsx
  fe/play-baseball-fe/pages/forgot-password/index.tsx
  src/main/java/org/example/spring/security/config/SecurityConfig.java
  src/main/java/org/example/spring/security/config/SecurityDevConfig.java
  src/main/java/org/example/spring/security/filter/MemberStatusCheckFilter.java
  src/main/java/org/example/spring/security/service/EmailService.java
Labels: ✨ Feature

#242 Refactor: MemberStatusCheckFilter 경로 변경
  src/main/java/org/example/spring/security/filter/MemberStatusCheckFilter.java
Labels: ✨ Feature

#243 Refactor: ExchangeLikeController, ExchangeLikeService의 addLike 반환 타입 변경
  src/main/java/org/example/spring/controller/ExchangeLikeController.java
  src/main/java/org/example/spring/service/ExchangeLikeService.java
Labels: 🔨 Refactor

#245 Refactor: 중고 거래 게시글 상세 정보에 좋아요 상태 추가
  src/main/java/org/example/spring/domain/exchange/dto/ExchangeDetailResponseDto.java
  src/main/java/org/example/spring/service/ExchangeService.java
Labels: 🔨 Refactor

#248 Chore: 도커파일 및 FE CD workflows 수정 및 자바독 추가
  .github/workflows/FE CD.yml
  fe/play-baseball-fe/.env.prod
  fe/play-baseball-fe/Dockerfile
  src/main/java/org/example/spring/security/filter/MemberStatusCheckFilter.java
  src/main/java/org/example/spring/security/filter/RateLimitFilter.java
Labels: 🔧 Chore

#250 Refactor: MemberResponseDto 필드 추가
  src/main/java/org/example/spring/domain/member/dto/MemberResponseDto.java
Labels: 🔨 Refactor

#251 Feat: 검색 기능 정상화, 최근 5개 글, 필터 관련 네비게이션 제작 외 기능 변경사항
  .github/workflows/FE CD.yml
  fe/play-baseball-fe/components/RecentExchangesNavigation.tsx
  fe/play-baseball-fe/components/SaleStatusNavigation.tsx
  fe/play-baseball-fe/components/SearchBar.tsx
  fe/play-baseball-fe/components/header.tsx
  fe/play-baseball-fe/constants/endpoints.tsx
  fe/play-baseball-fe/pages/index.tsx
  fe/play-baseball-fe/pages/search/index.tsx
  src/main/java/org/example/spring/controller/ExchangeController.java
  src/main/java/org/example/spring/repository/ExchangeRepository.java
  src/main/java/org/example/spring/service/ExchangeService.java
Labels: ✨ Feature, 💄 UI Design, 🔧 Chore

#253 Fix: DockerFile 환경변수 이름 변경 NEC -> NEXT_PUBLIC_NEC
  fe/play-baseball-fe/Dockerfile
Labels: 🐛 Bug Fix, 🔧 Chore

#256 #254 게시물 상세 페이지 내부 좋아요 기능 연동
  fe/play-baseball-fe/constants/endpoints.tsx
  fe/play-baseball-fe/pages/exchange/[id].tsx
  src/main/java/org/example/spring/controller/ExchangeLikeController.java
  src/main/java/org/example/spring/domain/exchange/dto/ExchangeDetailResponseDto.java
  src/main/java/org/example/spring/domain/like/ExchangeLike.java
  src/main/java/org/example/spring/service/ExchangeLikeService.java
  src/main/java/org/example/spring/service/ExchangeService.java
Labels: ✨ Feature

#257 Feat: MemberStatusCheckFilter 공개 엔드포인트 경로 추가
  src/main/java/org/example/spring/security/filter/MemberStatusCheckFilter.java
Labels: ✨ Feature

#261 Refactor: Exchange, Review, Like Controller Swagger 문서 업데이트
  .github/workflows/Spring CI.yml
  src/main/java/org/example/spring/controller/ExchangeController.java
  src/main/java/org/example/spring/controller/ExchangeLikeController.java
  src/main/java/org/example/spring/controller/ReviewController.java
Labels: ✨ Feature, 🔨 Refactor

#263 Feat: FE 배포 오류 수정
  .github/workflows/FE CD.yml
  README.md
  fe/play-baseball-fe/Dockerfile
  fe/play-baseball-fe/components/UserList.tsx
  src/main/java/org/example/spring/service/AuthService.java
Labels: 🐛 Bug Fix

#269 Feat: 잘못된 공개 엔드포인트 처리 수정
  README.md
  src/main/java/org/example/spring/security/config/SecurityConfig.java
  src/main/java/org/example/spring/security/config/SecurityDevConfig.java
  src/main/java/org/example/spring/security/filter/JwtValidatorFilter.java
  src/main/java/org/example/spring/security/filter/MemberStatusCheckFilter.java
Labels: 🐛 Bug Fix

#271 Fix: 비로그인 시 상세조회 페이지 버그 수정, 게시물 수정 시 기존 이미지 삭제되도록 변경
  fe/play-baseball-fe/pages/exchange/write/[id].tsx
  src/main/java/org/example/spring/service/ExchangeService.java
Labels: 🐛 Bug Fix

#273 Fix: 회원가입 성공 시 렌더링 오류, 로그인 시 새로고침해야 헤더에 반영되던 버그 수정
  fe/play-baseball-fe/pages/login/index.tsx
  fe/play-baseball-fe/pages/signup/index.tsx
Labels: 🐛 Bug Fix

#275 Docs: ReadMe 3안
  README.md
Labels: 📝 Documentation

#279 Docs: ReadMe update
  README.md
Labels: 📝 Documentation

#282 Refactor: 배포 자동화 main으로 한정하도록 변경
  .github/workflows/FE CD.yml
  .github/workflows/Spring CD.yml
Labels: 🔨 Refactor

#284 Fix: 게시물 등록, 수정시 새 제품 가격 로직 비동기 처리
  fe/play-baseball-fe/pages/exchange/[id].tsx
  src/main/java/org/example/spring/Application.java
  src/main/java/org/example/spring/repository/ExchangeRepository.java
  src/main/java/org/example/spring/service/AlanAPIService.java
  src/main/java/org/example/spring/service/ExchangeService.java
Labels: 🐛 Bug Fix

#292 Docs: 보안관련 클래스 자바독 추가
  README.md
  src/main/java/org/example/spring/controller/AuthController.java
  src/main/java/org/example/spring/security/config/MailConfig.java
  src/main/java/org/example/spring/security/config/SecurityConfig.java
  src/main/java/org/example/spring/security/filter/MemberStatusCheckFilter.java
  src/main/java/org/example/spring/security/service/AccountManagementService.java
  src/main/java/org/example/spring/security/service/CookieService.java
  src/main/java/org/example/spring/security/service/CustomUserDetailsService.java
  src/main/java/org/example/spring/security/service/CustomUsernamePasswordAuthenticationProvider.java
  src/main/java/org/example/spring/security/service/EmailService.java
  src/main/java/org/example/spring/security/service/RateLimiterService.java
  src/main/java/org/example/spring/security/service/TokenBlacklistService.java
  src/main/java/org/example/spring/security/utils/AuthUtils.java
  src/main/java/org/example/spring/security/utils/JwtUtils.java
  src/main/java/org/example/spring/service/AuthService.java
  src/main/java/org/example/spring/service/MemberService.java
  src/test/java/org/example/spring/controller/MemberControllerTest.java
  src/test/java/org/example/spring/service/MemberServiceTest.java
Labels: 📝 Documentation

#298 배포 버전 1.2
  README.md
  fe/play-baseball-fe/components/header.tsx
  fe/play-baseball-fe/pages/chat/index.jsx
  fe/play-baseball-fe/pages/exchange/[id].tsx
  fe/play-baseball-fe/pages/exchange/write/[id].tsx
  fe/play-baseball-fe/pages/exchange/write/index.tsx
  fe/play-baseball-fe/pages/my/index.tsx
  src/main/java/org/example/spring/config/RedisConfig.java
  src/main/java/org/example/spring/controller/AuthController.java
  src/main/java/org/example/spring/domain/message/messageDto/MessageResponseDto.java
  src/main/java/org/example/spring/domain/message/messageDto/MessageRoomResponseDto.java
  src/main/java/org/example/spring/security/config/MailConfig.java
  src/main/java/org/example/spring/security/config/SecurityConfig.java
  src/main/java/org/example/spring/security/filter/MemberStatusCheckFilter.java
  src/main/java/org/example/spring/security/service/AccountManagementService.java
  src/main/java/org/example/spring/security/service/CookieService.java
  src/main/java/org/example/spring/security/service/CustomUserDetailsService.java
  src/main/java/org/example/spring/security/service/CustomUsernamePasswordAuthenticationProvider.java
  src/main/java/org/example/spring/security/service/EmailService.java
  src/main/java/org/example/spring/security/service/RateLimiterService.java
  src/main/java/org/example/spring/security/service/TokenBlacklistService.java
  src/main/java/org/example/spring/security/utils/AuthUtils.java
  src/main/java/org/example/spring/security/utils/JwtUtils.java
  src/main/java/org/example/spring/service/AuthService.java
  src/main/java/org/example/spring/service/MemberService.java
  src/main/java/org/example/spring/service/MessageService.java
  src/test/java/org/example/spring/controller/MemberControllerTest.java
  src/test/java/org/example/spring/service/MemberServiceTest.java
Labels: 🐛 Bug Fix

#300 Refactor: ReviewRepository 테스트 코드 작성, LikeOverview 업데이트 시간 변경
  src/main/java/org/example/spring/service/LikeOverviewService.java
  src/test/java/org/example/spring/repository/ReviewRepositoryTest.java
Labels: 🔨 Refactor

#303 Fix: 채팅 500에러 관련 직렬화 문제 수정
  src/main/java/org/example/spring/domain/member/dto/MemberMessageResponseDto.java
  src/main/java/org/example/spring/domain/message/messageDto/MessageResponseDto.java
Labels: 🐛 Bug Fix

#304 Fix: MessageService 내용 누락하여 재업로드
  src/main/java/org/example/spring/service/MessageService.java
Labels: 🐛 Bug Fix

#305 Fix: 배포 버전 1.4
  src/main/java/org/example/spring/domain/member/dto/MemberMessageResponseDto.java
  src/main/java/org/example/spring/domain/message/messageDto/MessageResponseDto.java
  src/main/java/org/example/spring/service/MessageService.java
Labels: 🐛 Bug Fix
