Repository Ormi5-StrikeOut/Play-Baseball, pull requests merged in 2024-08, with the labels that each got.

#2 Chore: Gradle 의존성 정렬 및 .gitignore 템플릿 추가
  .gitignore
  build.gradle
Labels: 🔧 Chore

#8 [Feat] Create react app
  fe/play-baseball-fe/.eslintrc.json
  fe/play-baseball-fe/.gitignore
  fe/play-baseball-fe/README.md
  fe/play-baseball-fe/app/favicon.ico
  fe/play-baseball-fe/app/globals.css
  fe/play-baseball-fe/app/layout.tsx
  fe/play-baseball-fe/app/page.tsx
  fe/play-baseball-fe/next.config.mjs
  fe/play-baseball-fe/package-lock.json
  fe/play-baseball-fe/package.json
  fe/play-baseball-fe/postcss.config.mjs
  fe/play-baseball-fe/public/next.svg
  fe/play-baseball-fe/public/vercel.svg
  fe/play-baseball-fe/tailwind.config.ts
  fe/play-baseball-fe/tsconfig.json
Labels: ✨ Feature

#10 Feat: Member 엔티티 구현
  src/main/java/org/example/spring/constants/Gender.java
  src/main/java/org/example/spring/domain/Member.java
Labels: ✨ Feature

#18 Refactor: Member 엔티티 리펙터링
  src/main/java/org/example/spring/domain/Member.java
  src/main/java/org/example/spring/domain/member/Member.java
  src/main/java/org/example/spring/domain/member/MemberRole.java
Labels: 🔨 Refactor

#32 Feat: MemberRepository 구현
  src/main/java/org/example/spring/repository/MemberRepository.java
  src/test/java/org/example/spring/repository/MemberRepositoryTest.java
Labels: ✨ Feature

#35 Feat: Spring Security 기본 설정 구현
  src/main/java/org/example/spring/security/SecurityConfig.java
Labels: ✨ Feature

#33 Feat: MemberService 회원 등록 기능 구현
  src/main/java/org/example/spring/domain/member/dto/MemberJoinRequestDto.java
  src/main/java/org/example/spring/service/MemberService.java
  src/test/java/org/example/spring/service/MemberServiceTest.java
Labels: ✨ Feature

#42 Feat: MemberController 회원가입 엔드포인트 구현 및 ci test 관련 오류 수정
  .github/workflows/Spring CI.yml
  src/main/java/org/example/spring/common/ApiResponseDto.java
  src/main/java/org/example/spring/controller/MemberController.java
  src/test/java/org/example/spring/controller/MemberControllerTest.java
Labels: ✨ Feature

#48 Docs: Update issue templates
  .github/ISSUE_TEMPLATE/feat.md
Labels: 📝 Documentation

#50 Feat/#49 회원 전체 목록 조회 구현
  src/main/java/org/example/spring/controller/MemberController.java
  src/main/java/org/example/spring/domain/member/dto/MemberJoinRequestDto.java
  src/main/java/org/example/spring/domain/member/dto/MemberResponseDto.java
  src/main/java/org/example/spring/repository/MemberRepository.java
  src/main/java/org/example/spring/service/MemberService.java
  src/test/java/org/example/spring/controller/MemberControllerTest.java
  src/test/java/org/example/spring/repository/MemberRepositoryTest.java
  src/test/java/org/example/spring/service/MemberServiceTest.java
Labels: ✨ Feature

#52 Refactor/#51 MemberService 코드 리펙터링
  src/main/java/org/example/spring/domain/member/dto/MemberJoinRequestDto.java
  src/main/java/org/example/spring/domain/member/dto/MemberResponseDto.java
  src/main/java/org/example/spring/service/MemberService.java
  src/test/java/org/example/spring/repository/MemberRepositoryTest.java
  src/test/java/org/example/spring/service/MemberServiceTest.java
Labels: 🔨 Refactor

#56 Fix: 엔티티 테이블명 수정
  src/main/java/org/example/spring/domain/exchangeImage/ExchangeImage.java
  src/main/java/org/example/spring/domain/like/Like.java
  src/main/java/org/example/spring/domain/likeOverview/LikeOverview.java
  src/main/java/org/example/spring/domain/message/MessageMember.java
  src/main/java/org/example/spring/domain/message/MessageRoom.java
  src/main/java/org/example/spring/domain/review/Review.java
  src/main/java/org/example/spring/domain/reviewImage/ReviewImage.java
  src/main/java/org/example/spring/domain/reviewOverview/ReviewOverview.java
Labels: 🐛 Bug Fix

#36 Feat/#20 로그인 관련 페이지 레이아웃 작성
  fe/play-baseball-fe/.dockerignore
  fe/play-baseball-fe/Dockerfile
  fe/play-baseball-fe/app/page.tsx
  fe/play-baseball-fe/package-lock.json
  fe/play-baseball-fe/package.json
  fe/play-baseball-fe/pages/chat/[id].js
  fe/play-baseball-fe/pages/exchange/[id].js
  fe/play-baseball-fe/pages/forgot-password/index.tsx
  fe/play-baseball-fe/pages/index.js
  fe/play-baseball-fe/pages/login/index.tsx
  fe/play-baseball-fe/pages/member/[id].js
  fe/play-baseball-fe/pages/review/[id].js
  fe/play-baseball-fe/pages/search.js
  fe/play-baseball-fe/pages/signup/index.tsx
Labels: ✨ Feature

#58 Refactor: GlobalExceptionHandler BAD_REQUEST 메세지 수정
  src/main/java/org/example/spring/common/GlobalExceptionHandler.java
  src/test/java/org/example/spring/controller/MemberControllerTest.java
Labels: 🔨 Refactor

#60 Feat/#59 사용자 세부 정보 로드 및 인증 처리 기능 구현
  src/main/java/org/example/spring/repository/MemberRepository.java
  src/main/java/org/example/spring/security/CustomUserDetailsService.java
  src/main/java/org/example/spring/security/CustomeUsernamePasswordAuthenticationProvider.java
Labels: ✨ Feature

#62 Feat: 사용자 세부 정보 로드 및 인증 처리 기능 관련 테스트 코드 추가
  src/main/java/org/example/spring/security/CustomUserDetailsService.java
  src/main/java/org/example/spring/security/CustomUsernamePasswordAuthenticationProvider.java
  src/test/java/org/example/spring/security/CustomUserDetailsServiceTest.java
  src/test/java/org/example/spring/security/CustomUsernamePasswordAuthenticationProviderTest.java
Labels: ✅ Test
